name: Consul Tests

on:
  workflow_call:
    inputs:
      service_branch:
        required: false
        type: string
      versions_file:
        description: 'Path to versions list file'
        type: string
        required: true
      pipeline_branch:
        description: 'Test pipeline branch name'
        type: string
        required: true
        default: ${{ github.action_ref }}
      runner_type:
        description: 'Runner type (self-hosted or ubuntu-latest)'
        type: string
        required: false
        default: 'ubuntu-latest'
    secrets:
      AWS_S3_ACCESS_KEY_ID:
        required: true
      AWS_S3_ACCESS_KEY_SECRET:
        required: true

jobs:
  prepare-versions:
    runs-on: ${{inputs.runner_type}}
    outputs:
      versions: ${{steps.process-versions.outputs.versions}}
      previous_version: ${{steps.process-versions.outputs.previous_version}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: '${{inputs.service_branch}}'
          repository: 'Netcracker/qubership-consul'
          path: 'qubership-consul'
      - name: Process versions file
        id: process-versions
        run: |
          versions_str=$(cat qubership-consul/${{inputs.versions_file}})
          versions_json=$(echo $versions_str | jq -R -s -c 'split(" ")')
          echo "versions=$versions_json" >> $GITHUB_OUTPUT
          previous_version=$(echo "$versions_json" | jq -r '.[-1]')
          echo "previous_version=$previous_version" >> $GITHUB_OUTPUT

  # ---------- Current service branch ----------
  #4-Clean [LATEST_SPRINT], 5-Upgrade [LATEST_SPRINT] Diff Params
  Clean-Latest-Upgrade-Diff-Params:
    runs-on: ${{inputs.runner_type}}
    name: Clean [LATEST], Upgrade [LATEST] Diff Params
    steps:
      - name: Get current workflow branch
        id: get_branch
        run: |
          #echo ${{ github.action_ref }}
          COMMIT=$(echo "${{ github.event.workflow_call.uses }}" | awk -F '@' '{print $NF}')
          echo "Extracted commit: $COMMIT"
      - name: Checkout pipeline
        uses: actions/checkout@v4
        with:
          ref: ${{ github.action_ref }}
          repository: 'Netcracker/qubership-test-pipelines'
          path: 'qubership-test-pipelines'
      - name: Create cluster
        uses: ./qubership-test-pipelines/actions/shared/create_cluster
      #- name: Install Monitoring
        #uses: ./qubership-test-pipelines/actions/monitoring/helm_deploy_monitoring
      - name: Clean Install Consul [LATEST]
        uses: ./qubership-test-pipelines/actions/consul/helm_deploy_consul
        with:
          path_to_template: 'templates/consul-service/consul_clean_all_on_sc.yml'
          service_branch: '${{inputs.service_branch}}'
      - name: Verify Consul installation
        uses: ./qubership-test-pipelines/actions/consul/verify_installation_consul
      - name: Update to [LATEST] Version With Diff Params
        uses: ./qubership-test-pipelines/actions/consul/helm_deploy_consul
        with:
          path_to_template: 'templates/consul-service/consul_clean_all_on_sc_updated.yml'
          service_branch: '${{inputs.service_branch}}'
          deploy_mode: upgrade
      - name: Verify Consul upgrade
        uses: ./qubership-test-pipelines/actions/consul/verify_installation_consul

  #12-Clean [LATEST_SPRINT] Restricted
  Clean-Latest-Restricted:
    name: Clean [LATEST] Restricted
    runs-on: ${{inputs.runner_type}}
    steps:
#      - name: Checkout pipeline
#        uses: actions/checkout@v4
#        with:
#          ref: '${{inputs.pipeline_branch}}'
#          repository: 'Netcracker/qubership-test-pipelines'
#          path: 'qubership-test-pipelines'
      - name: Create cluster
        uses: ./qubership-test-pipelines/actions/shared/create_cluster
      - name: Clean Install Consul [LATEST] in Restricted mode
        uses: ./qubership-test-pipelines/actions/consul/helm_deploy_consul
        with:
          restricted: true
          path_to_template: 'templates/consul-service/consul_clean_all_on_sc_restricted.yml'
          service_branch: '${{inputs.service_branch}}'
      - name: Verify Consul installation
        uses: ./qubership-test-pipelines/actions/consul/verify_installation_consul

  #22-Clean [LATEST_SPRINT] Full-AT Ports-specifying Custom-labels
  Clean-Latest-Full-At-ports-Specifying-Custom-Labels:
    runs-on: ${{inputs.runner_type}}
    name: Clean [LATEST] Full-AT Ports-specifying Custom-labels
    steps:
#      - name: Checkout pipeline
#        uses: actions/checkout@v4
#        with:
#          ref: '${{inputs.pipeline_branch}}'
#          repository: 'Netcracker/qubership-test-pipelines'
#          path: 'qubership-test-pipelines'
      - name: Create cluster
        uses: ./qubership-test-pipelines/actions/shared/create_cluster
      - name: Clean Install Consul [LATEST] Full-At
        uses: ./qubership-test-pipelines/actions/consul/helm_deploy_consul
        with:
          path_to_template: 'templates/consul-service/consul_clean_all_on_sc_full_at.yml'
          service_branch: '${{inputs.service_branch}}'
      - name: Verify Consul installation
        uses: ./qubership-test-pipelines/actions/consul/verify_installation_consul

  #13-Clean [LATEST_SPRINT] W/O Components, 14-Upgrade [LATEST_SPRINT] All Components S3
  Clean-WO-Components-Upgrade-All-Components-S3:
    runs-on: ${{inputs.runner_type}}
    name: Clean [LATEST] W/O Components, Upgrade [LATEST] All Components S3
    steps:
#      - name: Checkout pipeline
#        uses: actions/checkout@v4
#        with:
#          ref: '${{inputs.pipeline_branch}}'
#          repository: 'Netcracker/qubership-test-pipelines'
#          path: 'qubership-test-pipelines'
      - name: Create cluster
        uses: ./qubership-test-pipelines/actions/shared/create_cluster
      - name: Clean Install Consul [LATEST] W/O Components
        uses: ./qubership-test-pipelines/actions/consul/helm_deploy_consul
        with:
          path_to_template: 'templates/consul-service/consul_clean_on_sc_without_components.yml'
          service_branch: '${{inputs.service_branch}}'
      - name: Verify Consul installation
        uses: ./qubership-test-pipelines/actions/consul/verify_installation_consul
      - name: Add secrets to template
        run: >-
          python qubership-test-pipelines/python/add_secrets_for_s3.py
          --path_to_file='qubership-test-pipelines/templates/consul-service/consul_clean_all_on_sc_drd_s3.yml'
          --key_id='${{secrets.AWS_S3_ACCESS_KEY_ID}}'
          --secret_key='${{secrets.AWS_S3_ACCESS_KEY_SECRET}}'
        shell: bash
      - name: Update Consul [LATEST] All Components S3
        uses: ./qubership-test-pipelines/actions/consul/helm_deploy_consul
        with:
          deploy_mode: upgrade
          path_to_template: 'templates/consul-service/consul_clean_all_on_sc_drd_s3.yml'
          service_branch: '${{inputs.service_branch}}'
      - name: Verify Consul installation
        uses: ./qubership-test-pipelines/actions/consul/verify_installation_consul

  #---------- Update from old releases ----------
  #6-Clean [N1_RELEASE], 7-Upgrade From [N1_RELEASE] To [LATEST_SPRINT]
  #8-Clean [N2_RELEASE], 9-Upgrade From [N2_RELEASE] To [LATEST_SPRINT]
  Clean-Previous-Update-To-Latest:
    name: Clean [PREVIOUS], Update to [LATEST]
    needs: prepare-versions
    runs-on: ${{inputs.runner_type}}
    strategy:
      matrix:
        release: ${{fromJson(needs.prepare-versions.outputs.versions)}}
    steps:
#      - name: Checkout pipeline
#        uses: actions/checkout@v4
#        with:
#          ref: '${{inputs.pipeline_branch}}'
#          repository: 'Netcracker/qubership-test-pipelines'
#          path: 'qubership-test-pipelines'
      - name: Create cluster
        uses: ./qubership-test-pipelines/actions/shared/create_cluster
      #- name: Install monitoring
        #uses: ./qubership-test-pipelines/actions/monitoring/helm_deploy_monitoring
      - name: Clean Install Consul [PREVIOUS]
        uses: ./qubership-test-pipelines/actions/consul/helm_deploy_consul
        with:
          path_to_template: 'templates/consul-service/consul_clean_all_on_sc.yml'
          service_branch: '${{matrix.release}}'
      - name: Verify Consul installation
        uses: ./qubership-test-pipelines/actions/consul/verify_installation_consul
        with:
          service_branch: '${{matrix.release}}'
      - name: Update Consul to [LATEST]
        uses: ./qubership-test-pipelines/actions/consul/helm_deploy_consul
        with:
          deploy_mode: upgrade
          path_to_template: 'templates/consul-service/consul_clean_all_on_sc.yml'
          service_branch: '${{inputs.service_branch}}'
      - name: Verify installation
        uses: ./qubership-test-pipelines/actions/consul/verify_installation_consul
        with:
          service_branch: ${{inputs.service_branch}}

  #10-Clean [PREVIOUS_SPRINT] Restricted, 11-Upgrade From [PREVIOUS_SPRINT] To [LATEST_SPRINT] Restricted
  Clean-Previous-Upgrade-To-Latest-Restricted:
    name: Clean [PREVIOUS] Restricted, Upgrade To [LATEST] Restricted
    needs: prepare-versions
    runs-on: ${{inputs.runner_type}}
    steps:
#      - name: Checkout pipeline
#        uses: actions/checkout@v4
#        with:
#          ref: '${{inputs.pipeline_branch}}'
#          repository: 'Netcracker/qubership-test-pipelines'
#          path: 'qubership-test-pipelines'
      - name: Get version
        run: echo ${{needs.prepare-versions.outputs.previous_version}}
      - name: Create cluster
        uses: ./qubership-test-pipelines/actions/shared/create_cluster
      - name: Clean Install Consul [PREVIOUS] in Restricted mode
        uses: ./qubership-test-pipelines/actions/consul/helm_deploy_consul
        with:
          restricted: true
          path_to_template: 'templates/consul-service/consul_clean_all_on_sc_restricted.yml'
          service_branch: '${{needs.prepare-versions.outputs.previous_version}}'
      - name: Verify Consul installation
        uses: ./qubership-test-pipelines/actions/consul/verify_installation_consul
        with:
          service_branch: '${{needs.prepare-versions.outputs.previous_version}}'
      - name: Update Consul to [LATEST] in Restricted mode
        uses: ./qubership-test-pipelines/actions/consul/helm_deploy_consul
        with:
          restricted: true
          deploy_mode: upgrade
          path_to_template: 'templates/consul-service/consul_clean_all_on_sc_restricted.yml'
          service_branch: '${{inputs.service_branch}}'
      - name: Verify Consul upgrade
        uses: ./qubership-test-pipelines/actions/consul/verify_installation_consul
        with:
          service_branch: ${{inputs.service_branch}}

  #18-Clean [LATEST_SPRINT] S3 TLS
  Clean-Latest-S3-TLS:
    name: Clean [LATEST] S3 TLS
    runs-on: ${{inputs.runner_type}}
    steps:
#      - name: Checkout pipeline
#        uses: actions/checkout@v4
#        with:
#          ref: '${{inputs.pipeline_branch}}'
#          repository: 'Netcracker/qubership-test-pipelines'
#          path: 'qubership-test-pipelines'
      - name: Create cluster
        uses: ./qubership-test-pipelines/actions/shared/create_cluster
      - name: Install cert-manager
        run: |
          helm repo add jetstack https://charts.jetstack.io --force-update
          helm upgrade --install cert-manager jetstack/cert-manager --namespace cert-manager \
            --create-namespace --version v1.16.3 --set prometheus.enabled=true   --set crds.enabled=true
      - name: Crate ClusterIssuer
        run: |
          kubectl apply -f - <<EOF
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: test-clusterissuer
          spec:
            selfSigned: {}
          EOF
      - name: Get clusterissuer
        run: kubectl get clusterissuer
      - name: Add secrets to template
        run: >-
          python qubership-test-pipelines/python/add_secrets_for_s3.py
          --path_to_file='qubership-test-pipelines/templates/consul-service/consul_clean_all_on_sc_drd_s3_tls.yml'
          --key_id='${{secrets.AWS_S3_ACCESS_KEY_ID}}'
          --secret_key='${{secrets.AWS_S3_ACCESS_KEY_SECRET}}'
      - name: Clean Install Consul [LATEST] S3 TLS
        uses: ./qubership-test-pipelines/actions/consul/helm_deploy_consul
        with:
          path_to_template: 'templates/consul-service/consul_clean_all_on_sc_drd_s3_tls.yml'
          service_branch: '${{inputs.service_branch}}'
      - name: Verify Consul installation
        uses: ./qubership-test-pipelines/actions/consul/verify_installation_consul
